### ISSUE TITLE
bibliographie (revue Tabularia)

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#10]
Bonjour,

Un problème que je ne sais résoudre.
Lors de l'import du fichier XML (dans l'archive jointe), la bibliographie n'est pas entièrement importée.
Le "checkbalisage" affiche : "Le champ [bibliographie] sera importé tronqué", toutes les références sont pourtant visibles à cette étape-ci. Lors de la visualisation, la bibliographie est effectivement tronquée.

Il s'agit d'un fichier pour la revue _Tabularia_.

Merci de votre aide,
Edith

[04zouache_testbiblio2.zip](https://github.com/metopes-openedition/coordination/files/646103/04zouache_testbiblio2.zip)

**Comment by jfriviere** [comment]
Le champ bibliographie dans Lodel était de type text (type MySQL TEXT). Je l'ai changé en LONGTEXT.
Ca devrait résoudre le pb.

**Comment by edithcannet** [comment]
En effet.
Merci.
