### ISSUE TITLE
[books] linguistique

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#11]
[http://edt.books.openedition.org/formation/6909]()
##Linguistique : exemples segmentés et alignement
````
//tei:quote[@type=exemple]
//tei:quote[@type=exemple]/tei:quote
//tei:quote[@type=exemple]/tei:quote/tei:num
//tei:quote[@type=exemple]/tei:quote/seg
//tei:quote[@type=exemple]/tei:quote[@type=traduction]
//tei:quote[@type=exemple]/tei:bibl
````
> Les notes sont-elles autorisées dans les exemples de linguistique ?

[chap05.zip](https://github.com/metopes-openedition/coordination/files/646414/chap05.zip)

**Comment by Myriam-Olivier** [comment]
> Oui

**Comment by CarolineTerrier** [comment]
[chap05.zip](https://github.com/metopes-openedition/coordination/files/693442/chap05.zip)

**Comment by Myriam-Olivier** [comment]
Voici le fichier dans lequel nous avons ajouté quelques notes qui passent bien quand on les importe en ligne.
