### ISSUE TITLE
[books] notes de bas de page, notes de fin

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#12]
[http://edt.books.openedition.org/formation/6911]()

## Notes de bas de page 
`//tei:note[@n][@place=foot]`
- 26 notes de bas de page ;
- la note **2** est composée de plusieurs paragraphes.

## Notes de fin
`//tei:note[@n][@place=end]`
- 5 notes de fin ;
- la note **i** est composée de plusieurs paragraphes.

> Sur la plateforme revues (espace de test : https://formations.lodel.org/10/formationcaen/7187), seuls les appels de note sont affichés, le texte des notes n'est pas affiché. Est-ce une limite au niveau de ce site de test ou la fonctionnalité n'est-elle pas disponible sur la plateforme revues ? 

[chap06.zip](https://github.com/metopes-openedition/coordination/files/646418/chap06.zip)

**Comment by CarolineTerrier** [comment]
Bonjour Édith,

Je n'accède pas à [https://formations.lodel.org/10/formationcaen/7187](https://formations.lodel.org/10/formationcaen/7187) : visiblement la page a été supprimée.

Merci.

**Comment by edithcannet** [comment]
Bonjour Caroline,

J'ai redéposé l'unité à cette adresse : https://formations.lodel.org/10/formationcaen/7530.

Merci.

**Comment by CarolineTerrier** [comment]
Bonjour Édith,

La fonctionnalité est disponible sur les deux plateformes. La problème d'affichage venait du modèle éditorial du site (qui a depuis été modifié par Jeff). À présent, les notes de fin s'affichent donc bien.
