### ISSUE TITLE
[revues] langue inverse

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#13]
[https://formations.lodel.org/10/formationcaen/7187]()

## Langue inverse (arabe)
Les éléments sont surbalisés pour le chargement sur les plateformes OpenEdition au moyen des attributs `@rend=rtl` et `@xml:lang=ar`.

### sous-titre
> L'affichage paraît correct.

### résumé
> L'affichage paraît correct.

### mots-clés
> Les mots-clés en arabe ne sont pas affichés.

### chaîne de caractères
> L'affichage paraît correct.

### citations
-  أقبل الليل يا حبيبي وناداني حنيني وسرت ذكراك طيفاً هام في بحر ظنوني
-  ينشر الماضي ظلالاً كان أُنساً وجمالا

> L'affichage paraît correct.

### paragraphe
*Paragraphes 7, 8 et 9 sur la plateforme.*
> L'affichage paraît correct.

### notes
*Notes 4 et 8.*
> L'affichage paraît correct.

[chap07.zip](https://github.com/metopes-openedition/coordination/files/646537/chap07.zip)

**Comment by CarolineTerrier** [comment]
La page [https://formations.lodel.org/10/formationcaen/7187](https://formations.lodel.org/10/formationcaen/7187) n'est pas accessible.
Merci.

**Comment by edithcannet** [comment]
https://formations.lodel.org/10/formationcaen/7531

Il vaut mieux continuer à faire les tests sur les deux plateformes en parallèle ou on peut privilégier un espace ?

**Comment by CarolineTerrier** [comment]
Bonjour,

La maquette, le modèle éditorial et les usages sont différents entre les plateformes Books et Revues. C'est pourquoi il importe de faire les tests sur les deux espaces, même si dans nombre de cas le résultat/notre réponse sera identique.
