### ISSUE TITLE
nouvelle version Schema tei.openedition.1.5 RC pour test

### ISSUE THREAD

**Issue by jfriviere** [metopes-openedition/coordination#15]
Bonjour Edith,
J'ai préparé un nouvelle version du schéma tei.openedition.
Les 2 modifications que j'ai apportées sont visibles ici : https://github.com/OpenEdition/tei.openedition/commit/9c83f153fab14f1751b4460ec98f660efacae86a
- reference to TEI P5 3.1.0
- fix the publicationStmt issue (valid with TEI P5 3.1.0)

Tu peux récupérer les xsd correspondants ici [tei.openedition.1.5.rc.zip](https://github.com/metopes-openedition/coordination/files/687032/tei.openedition.1.5.rc.zip)

Pourrais-tu tester qu'il valide correctement quelques exemples de TEI produits avec Metopes, en particulier les éléments `<publicationStmt>` utilisés dans le header ?

L'entête XML pour valider avec ce schéma : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<TEI 
	xmlns="http://www.tei-c.org/ns/1.0" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tei-c.org/ns/1.0 tei.openedition.1.5/tei.openedition.1.5.xsd">
```

Merci !
Jeff

**Comment by jfriviere** [comment]
tei.openedition.1.5.rc2 version corrigée autorisant plusieurs `<listBilb>` dans un `<div>`

[tei.openedition.1.5.rc2.zip](https://github.com/metopes-openedition/coordination/files/690031/tei.openedition.1.5.rc2.zip)

**Comment by edithcannet** [comment]
Bonjour,

À partir de tes réponses au ticket #4 et de ce schéma (v 1.5.), pas de problème de validation. 

Tout semble correct pour : 
- [x] `publicationStmt`
- [x] `listBibl`

(Meilleurs vœux à tous !)

**Comment by jfriviere** [comment]
Super Merci !
Et bonne année également !

**Comment by CarolineTerrier** [comment]
Bonjour,

Pour info, le xsd de cette version 1.5. n'a pas encore été ajouté sur cette page http://lodel.org/ns/.

**Comment by jfriviere** [comment]
La version 1.5 est publiée :  http://lodel.org/ns/tei.openedition.1.5/tei.openedition.1.5.xsd
http://lodel.org/ns/Changelog.txt
