### ISSUE TITLE
Styles de paragraphe, styles de caractère et hyperliens

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#16]
**URL** = [https://formations.lodel.org/10/formationcaen/lodel/]()
**Collection** = Pôle Document numérique
**Numéro** = Métopes – Dossier test
[https://formations.lodel.org/10/formationcaen/lodel/edition/index.php?id=7472
]()

Les **mêmes fichiers** déposés sur l'espace Books sont déposés sur l'espace revues.
Cf. [https://github.com/metopes-openedition/coordination/issues/5]() pour le contexte, la présentation des tickets, les fichiers joints à chaque ticket

**Points à contrôler**

- validité des fichiers XML-TEI par rapport au schéma TEI OpenEdition (**tei.openedition.1.5/tei.openedition.1.5.xsd**) ;
- production des PDF ;
- production des epub.

Les fichiers epub et PDF peuvent-ils nous être transmis en même temps que vos retours ?

------------------------------------------------------------

URL = [https://formations.lodel.org/10/formationcaen/7473]()

### adlocalPARA
Styles de paragraphe (préfixés) "adlocal" dans *Word* qui permet aux utilisateurs de créer des styles en attendant que les données (glossaire, sources des citations, titre traduit pour les titres de niveaux 2, 3…) soient traitées correctement dans la chaîne éditoriale.
	
- texte : *J’ai choisi, pour présenter ce sujet, de feuilleter avec soin cinq albums de photographies…*
- texte : *Un choix qui appelle les remarques suivantes…*

> sur la plateforme : `<p>`

### adlocalCAR
Même principe, en style de caractères.

- dans le paragraphe : *J’ai donc sélectionné dans un ensemble beaucoup plus divers, cinq ouvrages*

> sur la plateforme : texte sans balisage

### paragraphe de suite
Suite d'un paragraphe interrompu par une citation, une illustration.

- texte : *Ou L’Islande et mes sentiers imaginaires (1)*
- texte : *Ou dans L’Islande et mes sentiers imaginaires (2)*

> sur la plateforme : paragraphe non numéroté `<p rend=noindent>`

### hyperliens 

- notes 7 et 8.

[art01.zip](https://github.com/metopes-openedition/coordination/files/689428/art01.zip)

**Comment by CarolineTerrier** [comment]
**paragraphe de suite**
OK

**hyperliens**
OK

**adlocalCAR et adlocalPARA**
Voir [https://github.com/metopes-openedition/coordination/issues/6](https://github.com/metopes-openedition/coordination/issues/6)
