### ISSUE TITLE
[revues] auteurs, traducteur, références croisées, liens hypertextes

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#17]
URL = [https://formations.lodel.org/10/formationcaen/7475]()

### Plusieurs auteurs 
Auteur, affiliation, mail
> Les mails ne sont pas affichés. Est-ce un choix d'affichage dépendant de la maquette ?
> Les enrichissements typographiques sont-ils supportés dans les affiliations ?

### Traducteur
Balisage `teiHeader/fileDesc/titleStmt/editor[@role=trl]`.
> Son affiliation n’apparait pas, est-ce dépendant de la maquette ? 

### Références croisées internes
Les liens internes et références croisées sont balisés par des `<ref>` et `<anchor/>` `@type=crossref`.
> Plateforme OE : ce balisage est supprimé (références et ancres) dans le fichier pour Lodel.

### Liens hypertextes
Balisage : `//ref[@target]`
- texte : notes 4 et 5
> Liens actifs.

[art02.zip](https://github.com/metopes-openedition/coordination/files/689431/art02.zip)

**Comment by jfriviere** [comment]
> Les mails ne sont pas affichés. Est-ce un choix d'affichage dépendant de la maquette ?

-> oui

> Les enrichissements typographiques sont-ils supportés dans les affiliations ?

->Non (ils peuvent être présents mais seront ignorés par Lodel lors de l'import)

> Tracuteur  : Son affiliation n’apparait pas, est-ce dépendant de la maquette ?

-> oui

**Comment by jfriviere** [comment]
Sur les enrichissement typo dans les affiliations, ils sont supportés si on utilise l'attribut `rendition` mais pas si on utilise l'attribut `rend` (bug Lodel). 
cf. https://github.com/metopes-openedition/coordination/issues/7

**Comment by CarolineTerrier** [comment]
**Liens hypertextes** 

Dans le document exemple, il y a des éléments non nécessaires (liés au HTML ?). Par exemple dans la note de bas de page 4, je les ai entourés en rouge :

![2017-01-13_12h52_55](https://cloud.githubusercontent.com/assets/23495863/21929180/65d3e0ee-d98f-11e6-97d3-88abaa8d4278.png)

Je ne crois pas que ces entités posent problème, mais je n'en suis pas certaine. En revanche, je suis certaine qu'elles ne sont pas nécessaires pour les liens hypertextes. Mieux vaut donc les supprimer.

**Comment by jfriviere** [comment]
(je vois passer ce message)
Elles ne sont pas nécessaires mais je pense que c'est au choix de l'éditeur d'afficher ou non les urls cliquables entre chevrons (<>). Dans l'exemple elle sera affichée sous cette forme :
`<http://URL>`

**Comment by edithcannet** [comment]
Il s'agit bien d'un choix de l'éditeur ; utiliser des chevrons pour encadrer les liens hypertextes. 
Voir ci-dessous capture du fichier interprété dans un éditeur XML.

<img width="1120" alt="chevrons_entite" src="https://cloud.githubusercontent.com/assets/15359081/21964301/e781cadc-db49-11e6-847b-a9c3807c0f52.png">
