### ISSUE TITLE
Sous-titre, bibliographie, Citation (langue du texte), ancres et références croisées 

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#18]
URL = [https://formations.lodel.org/10/formationcaen/7476]()

### Sous-titre
`front/titlePage/docTitle/titlePart[@type="sub"]`

- texte : *Exploration de l’univers mental islandais à travers le roman Sur la paupière de mon père*

### Bibliographie structurée
`back/div[@type=bibliographie]/listBibl`
> Fichier invalide par rapport au schéma **tei.openedition.1.5/tei.openedition.1.5.xsd**.
> Il faut un seul élément `<listBibl>` dans la `div type="bibliography"` ? 
> Quelle est le balisage attendu ?

### Citation dans la langue du texte 
Distinction des citations dans la **langue principale** du texte, dans une **langue autre**.
`//quote[@rend=quotation | quotation italique]`

Deux modalités : inline (styles de caractères) ou block (style de paragraphe).

- une citation en langue principale suivie d'une citation en langue autre
	- texte : *Sjálfsagt botna ég jafn lítið* 
	- et *De toute évidence, je comprends tout aussi peu la réalité qu’elle me comprend, moi.* 	

> - Par défault, les citations en langue autre sont rendues en italique sur la plateforme.
> - Tests ultérieurs pour le paramétrage utilisateur définissant le rendu souhaité (romain ou italique)

- deux citations en langue principale consécutives
	- texte : *Que le monde, pour les anciens Scandinaves…*

- citation inline
Balisage de citations non dégagées, conservées à l'intérieur de paragraphe, `//p/quote[@style]`;
	- texte : *une petite fleur d’éternité couverte de larmes tremblantes*

> Balisage supprimé dans le fichier pour Lodel.

- citation avec retours forcés
`//quote/lb`
	- texte : *Menaces d’orage sur l’hémisphère Nord.*

### Ancres et références croisées externes
Références croisées entre plusieurs document `<ref>` et `<anchor/>`.
> Filtrer pour la plateforme.

[art03.zip](https://github.com/metopes-openedition/coordination/files/689464/art03.zip)

**Comment by jfriviere** [comment]
La structuration de la bibliographie est correcte. C'est une erreur dans le schema TEI.
voici une version corrigée 
[tei.openedition.1.5.rc2.zip](https://github.com/metopes-openedition/coordination/files/690031/tei.openedition.1.5.rc2.zip)

**Comment by CarolineTerrier** [comment]
**Sous-titre** 
OK

**Citation dans la langue du texte**
Réponse identique à [https://github.com/metopes-openedition/coordination/issues/8](https://github.com/metopes-openedition/coordination/issues/8).

**Ancres et références croisées externes**
C'est parfait.
