### ISSUE TITLE
Tableau et Image

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#19]
URL = [https://formations.lodel.org/10/formationcaen/7478]()	
### Tableau
Définition CSS par cellule `teiHeader/encodingDesc/tagsDecl`. 
- ici, fonds grisé sur la rangée d'en-tête, bordures standards.
> Ce rendu est-il respecté dans l'epub et le PDF produits ?

### Image
- fig 1 : titre seul
- fig 2 : titre et légende
- fig 3 : titre seul
- fig 4 : titre, légende, crédits

[art04.zip](https://github.com/metopes-openedition/coordination/files/689477/art04.zip)

**Comment by CarolineTerrier** [comment]
**Tableau**

Le tableau dépasse de la maquette (sur le HTML, il est coupé : la fin est invisible). On va donc se retrouver avec des problèmes dans les formats détachables. La réponse est ici la même que pour Books : quand le tableau est trop large pour notre maquette, nous recommandons soit d'en faire une image, soit (quand c'est possible) de le diviser (Voir [https://github.com/metopes-openedition/coordination/issues/9](https://github.com/metopes-openedition/coordination/issues/9)).

**Comment by CarolineTerrier** [comment]
**Image**

OK
