### ISSUE TITLE
@role <author> | <editor>

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#2]
[Rôles des auteurs et collaborateurs – Unité éditoriale.docx](https://github.com/metopes-openedition/coordination/files/595083/Roles.des.auteurs.et.collaborateurs.Unite.editoriale.docx)

Tableau des attributs **@role** du _Marc21_ implémentés dans _Métopes_ pour les unités éditoriales.

Que doivent devenir ces structures pour _Lodel_ ?

**Comment by CarolineTerrier** [comment]
Bonjour Édith,
Cette question (ainsi que celle des types des unités éditoriales correspondant à la Z 39-98) n'est pas oubliée. Le service Revues doit se réunir la semaine prochaine pour en discuter. Nous vous tiendrons informés.

**Comment by CarolineTerrier** [comment]
**Concernant ce tableau :**
![tableaux des roles des editor des puc](https://cloud.githubusercontent.com/assets/23495863/21723255/106e1d7c-d430-11e6-9628-6552877eca81.jpg)


1) **Traducteur** : Chez OpenEdition, OK pour /tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:editor[@role='translator']

2) **Éditeur scientifique** : Chez OpenEdition OK pour /tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:editor[not(@role)]

3) **L’ensemble chercheur, photographe, illustrateur, dessinateur, cartographe, compilateur, collaborateur, annotateur et auteur secondaire**.
Aucun ne sera pris en compte avec une entrée TEI “editor”.
Cependant, nous aimerions, si c'est possible de votre côté, que la moulinette des PUC reprenne ces entrées afin qu’elles s’affichent dans la “Note de la rédaction” sous une forme du type :
“Ont participé à ce document : Charles Fos (annotateur)  ; Mireille Dan et Samuel Drouen (illustrateurs).”

- Pour Revues.org : nous aimerions que cela puisse se faire au niveau de l'unité éditoriale (en “Note de la rédaction”).
- Pour OpenEdition Books : nous aimerions que cela puisse se faire non seulement au niveau de l'unité éditoriale, mais aussi à celle du volume (en note de l'éditeur). 
=> Cela vous semble-t-il possible ? 

4) **Directeur de fouilles** :  Chez OpenEdition, OK pour /tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:editor[@role='excavationsdirector']

5) **Par ailleurs, nous réservons "collaborateur” aux seuls collaborateurs de fouille** (qu'on trouve principalement dans les publications d'archéologie) : /tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:editor[@role='collaborator']. Vous pouvez ajouter cette entrée à votre tableau, en gardant toutefois à l'esprit que Lodel n'affiche pas ce rôle par défaut. La pertinence de cette fonction doit en effet être discutée au cas par cas en amont entre l'éditeur et un chargé d’édition (qui pourra, le cas échéant, procéder à l'adaptation du site nécessaire). 

Bonne journée.
