### ISSUE TITLE
[Books] Dates de publication renseignées dans le chapitre

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#22]
URL de connexion : [http://edt.books.openedition.org/formation/6949](url)

Sur books, la date de publication est renseignée au niveau du volume, dans le manifest.xml.

Quelles sont les conséquences si cette information est aussi présente dans les métadonnées (uniquement dans les métadonneés) du chapitre ?

[Socio_4_03_Boullier.zip](https://github.com/metopes-openedition/coordination/files/712283/Socio_4_03_Boullier.zip)

**Comment by CarolineTerrier** [comment]
Sur OpenEdition Books, Lodel ne récupère pas de date au niveau des chapitres lorsque cette date est présente dans les métadonnées (et uniquement dans les métadonnées) d'une source en XML.  Ainsi, lorsqu'une telle date demeure dans le fichier source XML, c'est sans conséquence : elle n'est nullement prise en compte par Lodel.
