### ISSUE TITLE
schéma TEI :  <link> ; <meeting> ; <nameLink>  ; <relatedItem>

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#3]
Bonjour,

À quoi servent les balises TEI : 
- link ;
- meeting ;
- nameLink ;
- relatedItem ?

Pouvez-vous me donner des exemples d'utilisation ?
Nous procédons à une nouvelle comparaison des schémas TEI Métopes et TEI Open Edition.

Merci.

**Comment by CarolineTerrier** [comment]
Bonjour Édith,

Nous n'avons aucun usage de ces éléments pour Revues.org comme pour Books.
Il ne faut donc pas en tenir compte.
Très cordialement,
