### ISSUE TITLE
schéma TEI : <publisher>, <appInfo> et noms des auteurs

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#4]
Bonjour,

Quelques questions pour valider les fichiers XML-TEI produits avec Métopes par rapport au schéma 
**http://lodel.org/ns/tei.openedition.1.4.1/tei.openedition.1.4.1.xsd**.

– L'élément `<publisher>` semble obligatoire à 2 endroits :
```
TEI/teiHeader/fileDesc/publicationStmt/
TEI/teiHeader/fileDesc/sourceDesc/biblFull/publicationStmt/

```
Quelle donnée doit y figurer ?
Comment cette information est stylée dans le **.doc** soumis à Lodel (cas de production hors de la chaîne Métopes) ?

– Doit-on modifier des éléments et/ou attributs dans l’encodage de l’élément `<appInfo>` pour documenter les fichiers produits avec la chaîne Métopes?
`TEI/teiHeader/encodingDesc/appInfo/`

Sinon, ce balisage est-il correct : 
```
<appInfo>
   <application ident=lodel version=1.0>
      <label> Lodel – CLEO – Métopes</label>
      <desc>Généré à partir d'un fichier source XML-TEI (chaîne éditoriale Métopes)</desc>
   </application>
</appInfo>
```

– Les noms doivent-ils être balisé en 
```
<persName>
   <forename></forename>
   <surname></surname>
</persName>
```
?
Quels sont les xPath ?

Merci,
Edith

**Comment by jfriviere** [comment]
`<publisher>` est obligatoire dans publicationStmt mais ça ne sera plus le cas dans la version 1.5 de tei.openedition. La contrainte sera basé sur tei_all.xsd (P5 3.1.0) : `<publicationStmt>` devra contenir un de ces éléments `<p>`, `<ab>`, `<publisher>`


OTX ne renseigne pas de `<publisher>` et produit donc des fichiers invalides par rapport à ce schema.
Pour le moment, tu peux ajouter `<publisher />` dans `<publicationStmt>` .

**Comment by jfriviere** [comment]
> Doit-on modifier des éléments et/ou attributs dans l’encodage de l’élément <appInfo> pour documenter les fichiers produits avec la chaîne Métopes?
> TEI/teiHeader/encodingDesc/appInfo/

Je ne comprends pas la question.

> Sinon, ce balisage est-il correct :
> 
 ```xml 
<appInfo>
    <application ident=lodel version=1.0>
       <label> Lodel – CLEO – Métopes</label>
       <desc>Généré à partir d'un fichier source XML-TEI (chaîne éditoriale Métopes)</desc>
    </application>
 </appInfo>
```

Presque, avec des quotes autour des attributs,  il l'est : 
```xml
<appInfo>
   <application ident="lodel" version="1.0">
      <label> Lodel – CLEO – Métopes</label>
      <desc>Généré à partir d'un fichier source XML-TEI (chaîne éditoriale Métopes)</desc>
   </application>
</appInfo>
```

**Comment by jfriviere** [comment]
pour les noms, on peut utiliser la balise `<name>` https://github.com/OpenEdition/tei.openedition/wiki/Composer-un-document-en-TEI-pour-Lodel-1.0#utilisation-de-la-balise-name

ou `<persName>` https://github.com/OpenEdition/tei.openedition/wiki/Composer-un-document-en-TEI-pour-Lodel-1.0#utilisation-de-la-balise-persname
comme tu l'indiques :
```xml
<persName>
   <forename>Jean-François</forename>
   <surname>Rivière</surname>
</persName>
```

Si tu as le choix, il vaut mieux utiliser `<persName>`

**Comment by CarolineTerrier** [comment]
Le service Books et le service Revues ont une demande commune.
Serait-il possible d'afficher la version de l'outil Métopes ayant servi à produite le fichier XML dans : 
<appInfo>
   <application ident="lodel" version="1.0">
      <label> Lodel – CLEO – Métopes</label>
      <desc>Généré à partir d'un fichier source XML-TEI (chaîne éditoriale Métopes)</desc>
   </application>
</appInfo>
?
