### ISSUE TITLE
[books] adlocal, paragraphe de suite

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#6]
### adlocalPARA
Styles de paragraphe (préfixés) "adlocal" dans *Word* qui permet aux utilisateurs de créer des styles en attendant que les données (glossaire, sources des citations, titre traduit pour les titres de niveaux 2, 3…) soient traitées correctement dans la chaîne éditoriale.
	
- texte : *J’ai choisi, pour présenter ce sujet, de feuilleter avec soin cinq albums de photographies…*
- texte : *Un choix qui appelle les remarques suivantes…*

> sur la plateforme : `<p>`

### adlocalCAR
Même principe, en style de caractères.

- texte : *J’ai donc sélectionné dans un ensemble beaucoup plus divers, cinq ouvrages*

> sur la plateforme : texte sans balisage

### paragraphe de suite
Suite d'un paragraphe interrompu par une citation, une illustration.
- texte : *Ou L’Islande et mes sentiers imaginaires (1)*
- texte : *Ou dans L’Islande et mes sentiers imaginaires (2)*

> sur la plateforme : paragraphe non numéroté `<p rend=noindent>`

[chap01.zip](https://github.com/metopes-openedition/coordination/files/630551/chap01.zip)

**Comment by Myriam-Olivier** [comment]
### adlocalPARA
Demande de précisions nécessaire : On ne peut pas généraliser la conversion de ce style de paragraphe en paragraphe normal sur la plateforme. C'est le cas par exemple pour les sources de citations, auxquelles on pourra appliquer un style de citation, ou les titres traduits pour les intertitres, qu'on pourra accoler directement aux titres originaux à l'intérieur d'un même intertitre. Il faudrait donc préciser chacun de ces cas, avec l'intention première de l'utilisateur. Dans l'exemple présenté, on ne saisit pas quels sont la sémantisation et le style visés et en quoi le paragraphe diffère d'un paragraphe courant. 
### adlocalCAR
Même remarque : pourquoi appliquer ici un style adlocalCAR ? Peut-on donc préciser à quoi correspond le style adlocalCAR : pouvez-vous nous donner des exemples ?
### paragraphe de suite
Oui, point validé. On utilisera dans ce cas le paragraphe non numéroté.

**Comment by edithcannet** [comment]
Il y a, schématiquement, deux cas de recours aux surcharges "adlocal" : 
- les lacunes dans la chaîne : nous ne traitons pas pour le moment les sources des citations, les glossaires, les intertitres traduits, etc. ;
- les surcharges qui facilitent la mise en forme (création d'autant de styles de paragraphes et de caractères dans InDesign et de class pour les epubs).

Dans le premier cas, effectivement, l'objectif est bien de sémantiser ces éléments et de les encoder correctement en TEI. Nous pourrons ouvrir un ticket listant les demandes d'implémentations et choisir un encodage commun.

Dans tous les cas, la conversion des surcharges "adlocal" en texte courant pour les plateformes est à voir plus comme un comportement par défaut en attendant de sémantiser ces éléments et de leur attribuer un rendu.

**Comment by Myriam-Olivier** [comment]
### adlocalCAR
Pour les styles adlocalCAR, le comportement par défaut pourrait être le simple héritage du style du paragraphe englobant. Si on a une police de couleur différente par exemple, ce serait la couleur du paragraphe normal (donc noir par défaut) qui prévaudrait. 

### adlocalPARA
Le nombre de cas représentés par ce style étant très nombreux, il n'est pas sûr que nous parvenions à ce niveau de correspondance pour un encodage sémantisé commun. Il nous semble plus réaliste de partir sur un comportement par défaut, en ajoutant une note à l'attention des utilisateurs les informant de la conversion des données (et les invitant éventuellement à modifier le balisage pour la sortie Lodel).
