### ISSUE TITLE
[books] auteurs, traducteur, références croisées, liens hypertextes

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#7]
[http://edt.books.openedition.org/formation/6904]()
### Plusieurs auteurs 
Auteur, affiliation, mail
> Les mails ne sont pas affichés. Est-ce un choix d'affichage dépendant de la maquette ?
> Les enrichissements typographiques sont-ils supportés dans les affiliations ?

### Traducteur
Balisage `teiHeader/fileDesc/titleStmt/editor[@role=trl]`.
> Son affiliation n’apparait pas, est-ce dépendant de la maquette ? 

### Références croisées internes
Les liens internes et références croisées sont balisés par des `<ref>` et `<anchor/>` `@type=crossref`.
> Plateforme OE : ce balisage est supprimé (références et ancres) dans le fichier pour Lodel.

### Liens hypertextes
Balisage : `//ref[@target]`
- texte : notes 4 et 5
> Liens actifs.

[chap02.zip]()

**Comment by Myriam-Olivier** [comment]
### Plusieurs auteurs
Les mails ne sont effectivement pas affichés car seule la balise de description d'auteur s'affiche dans la maquette. Les enrichissements typographiques sont supportés dans ces balises `<affiliation>` sous la forme de simples css. 
### Traducteur
Il s'agit en effet d'un bug d'affichage dans la maquette, que nous devons régler en interne pour Books comme pour Revues.
### Références croisées internes
Les références croisées internes, à l'exception des notes, ne sont pas possibles sur la plateforme. Confirmez-vous que le balisage est supprimé au moment de la conversion vers OE ?
### Liens hypertextes
Ce balisage est correct pour les liens hypertextes. Pour la rétro-numérisation, nous désactivons les hyperliens si nous n'avons pas les moyens de tous les vérifier, car si ces derniers sont défectueux nous pouvons rencontrer des blocages au niveau des revendeurs pour les formats détachables.

**Comment by jfriviere** [comment]
Sur les enrichissement typo dans les affiliations, ils sont supportés si on utilise l'attribut `rendition` mais pas si on utilise l'attribut `rend` (bug Lodel). 
cf. https://github.com/metopes-openedition/coordination/issues/17

**Comment by edithcannet** [comment]
### Général
Vous est-il possible d'activer l'affichage de tous les éléments (mail, traducteur et affiliation, annexes et bibliographies longues, maquette pour la langue arabe, etc.) sur les deux espaces de test ? 

### Références croisées internes
Le balisage est bien supprimé, sans substitution.

**Comment by CarolineTerrier** [comment]
**Concernant les éléments de la description auteur** 

Sur les plateformes Books et Revues, pour la description des auteurs nous n'utilisons qu'un type de balise : `<affiliation>`.
Il n'est pas dans nos usages d'utiliser les balises : `<email>, <roleName>, <orgName>`. En pratique, les informations qui pourraient être contenues dans ces balises sont donc placées dans `<affiliation>`.

Merci.
