### ISSUE TITLE
[books] bibliographie structurée, citations

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#8]
[http://edt.books.openedition.org/formation/6905]()	
### Bibliographie structurée
`back/div[@type=bibliographie]/listBibl`
> Le balisage produit valide est-il valide par rapport à votre schéma ?
> Les niveaux de titres dans la bibliographie devraient-ils apparaître dans la table des matières ?

### Citation dans la langue du texte 
Distinction des citations dans la **langue principale** du texte, dans une **langue autre**.
`//quote[@rend=quotation | quotation italique]`

Deux modalités : inline (styles de caractères) ou block (style de paragraphe).

- une citation en langue principale suivie d'une citation en langue autre
	- texte : *Sjálfsagt botna ég jafn lítið* 
	- et *De toute évidence, je comprends tout aussi peu la réalité qu’elle me comprend, moi.* 	

> - Par défault, les citations en langue autre sont rendues en italique sur la plateforme.
> - Tests ultérieurs pour le paramétrage utilisateur définissant le rendu souhaité (romain ou italique)

- deux citations en langue principale consécutives
	- texte : *Que le monde, pour les anciens Scandinaves…*

- citation inline
Balisage de citations non dégagées, conservées à l'intérieur de paragraphe, `//p/quote[@style]`;
	- texte : *une petite fleur d’éternité couverte de larmes tremblantes*

> Balisage supprimé dans le fichier pour Lodel.

- citation avec retours forcés
`//quote/lb`
	- texte : *Menaces d’orage sur l’hémisphère Nord. *

### Ancres et références croisées externes
Références croisées entre plusieurs document `<ref>` et `<anchor/>`.
> Filtrer pour la plateforme.

[chap03.zip](https://github.com/metopes-openedition/coordination/files/631149/chap03.zip)

**Comment by CarolineTerrier** [comment]
**Bibliographie structurée**

- Pour valider un document selon notre schéma, voir la procédure ici : [https://github.com/metopes-openedition/coordination/issues/15](https://github.com/metopes-openedition/coordination/issues/15)

- En ce qui concerne la table des matières : sur Books, il n'y a pas de table détaillée au niveau du chapitre, il est donc normal que ces intertitres ne soient pas présents dans la table.

- Je reviendrai ultérieurement sur les intertitres qui ne passent pas sur le document.


**Citation dans la langue du texte**

1) **Une citation en langue principale suivie d'une citation en langue autre** 
Pour Revues comme pour Books, nous aimerions que par défaut le paramétrage mette la langue étrangère en romain. L'italique devenant alors une option volontairement choisie par l'éditeur/l'auteur. Et ce, entre autres, afin d'éviter que le grec ou l'arabe (par exemple) puissent automatiquement avoir un rendu en italique.
OK pour le balisage de [http://edt.books.openedition.org/formation/6905](http://edt.books.openedition.org/formation/6905) à ce sujet.

2) **Deux citations en langue principale consécutives**
OK

3) **Citation inline**
OK

4) **Citation avec retours forcés**
OK


**Ancres et références croisées externes**

Est-ce que cela signifie que votre moulinette pour l'export en XML vers Lodel supprime automatiquement ces balises dans le document ?
Si c'est le cas, c'est parfait. En effet, les références croisées ne peuvent pas exister sous cette forme sur nos plateformes (mais on peut par exemple les remplacer par des références hypertextes [//tei:ref[@target]).


J'en profite également pour vous souhaiter une très belle année 2017. Qu'elle vous soit faste !

**Comment by edithcannet** [comment]
### Bibliographie structurée

- Problème de validation résolu avec le nouveau schéma.
- J'attends les remarques sur les intertitres.

### Citation dans la langue du texte
    
**1. Une citation en langue principale suivie d'une citation en langue autre**

Par défaut, nous préférerions laisser les citations en langue autre en *italique*, ce qui correspond aux pratiques éditoriales.
L'utilisateur peut – par contre – choisir de les paramétrer en romain cf. capture ci-dessous.

Il faudra trouver une solution lors de la cohabitation trois langues de citations avec des rendus différents…

À terme, le rendu des citations ne pourrait-il pas être géré par la maquette de site ?
Sur la base des distinctions qui étaient faites : `tei:q[@rend='quotation'|'quotation2'|'quotation3']`.

<img width="696" alt="param-quote" src="https://cloud.githubusercontent.com/assets/15359081/21761160/5da93932-d651-11e6-9096-20bd39962750.png">

Même unité chargée à cette adresse, avec la citation en langue autre en romain :  [http://edt.books.openedition.org/formation/6930]()

### Ancres et références croisées externes
Balisage supprimé lors de l'export pour les plateformes OE.

**Comment by CarolineTerrier** [comment]
**Concernant les citations en langue(s) étrangère(s)**

■ L'italique pour ces citations est une convention relative au papier. Par ailleurs, ce n'est pas un standard international de l'édition et nos plateformes accueillent des éditeurs non francophones. Nous ne voulons donc pas que  l'italique soit paramétré par défaut sur vos outils, mais bien le romain.

■ Lorsqu'il y a des citations en trois langues et (le cas semble rare) que l'éditeur désire un rendu différent pour chacune : il peut utiliser le style "Citation bis" (//tei:q[@rend='quotation2']), ou "Citation ter" (//tei:q[@rend='quotation3']) s'il a déjà un usage défini de "Citation bis", et appliquer au texte concerné la mise en forme italique.

■ Nous réfléchissons en effet à un éventuel devenir de nos trois styles de citation, mais dans la perspective de la mise en place de Journals et d'une maquette générique. Nous n'envisageons aucune modification avant cette mise en place.

Bien cordialement,

**Comment by CarolineTerrier** [comment]
**Intertitres dans la bibliographie**

Pour les intertitres dans la bibliographie, le problème a été résolu : ils s'affichent.
