### ISSUE TITLE
[books] tableau, image

### ISSUE THREAD

**Issue by edithcannet** [metopes-openedition/coordination#9]
[http://edt.books.openedition.org/formation/6906]()	
### Tableau
Définition CSS par cellule `teiHeader/encodingDesc/tagsDecl`. 
- ici, fonds grisé sur la rangée d'en-tête, bordures standards.
> Ce rendu est-il respecté dans l'epub et le PDF produits ?
### Image
- fig 1 : titre seul
- fig 2 : titre et légende
- fig 3 : titre seul
- fig 4 : titre, légende, crédits
[chap04.zip](https://github.com/metopes-openedition/coordination/files/631166/chap04.zip)

**Comment by Myriam-Olivier** [comment]
### Tableau
Le rendu est bien maintenu dans l'Epub et le PDF. Cependant, la largeur du tableau dépasse la largeur de la maquette et pose problème dans les formats détachables. Voir résultat dans le PDF généré ci-dessous (l'epub ne passe pas dans les tickets, je vous le transmets par e-mail). 

[puc-9991.pdf](https://github.com/metopes-openedition/coordination/files/692964/puc-9991.pdf)

**Comment by edithcannet** [comment]
### Tableau
Vous recommandez d'en faire une image ?

Avoir deux formalismes pour un même tableau est-il envisageable : l'un en texte pour les pages html, l'un en image pour les formats détachables ? 

### Notes dans l'epub
Il n'y a pas d'espace entre le numéro de la note et le corps de la note lorsque cette dernière commence par une portion de texte en italique.

> fichier XML-TEI : aucun espace en début de note.

Mise en parallèle du rendu epub et du rendu html : 
<img width="1133" alt="notes" src="https://cloud.githubusercontent.com/assets/15359081/21761277/29b5403e-d652-11e6-92a2-351c23b679ac.png">

**Comment by Myriam-Olivier** [comment]
### Tableau
Oui, nous recommandons d'en faire une image ou bien de diviser le tableau en deux sections. Deux formalismes ne sont pas envisageables puisque tous les formats sont générés à partir d'un même format pivot. 

### Notes dans l'Epub
C'est effectivement un bug dans la maquette de l'Epub qu'il faudrait corriger.

**Comment by edithcannet** [comment]
### Tableau 

Deux pistes nous semblent intéressantes à explorer (par ordre de préférence ) : 

1. utiliser la commande css `word-break` : 
autorise la césure des mots et donc la réduction de la largeur des tableaux ;

> valide epubcheck

2. encoder dans le fichier pivot un lien vers l'image du tableau à afficher et une transcription du contenu en texte pour permettre la recherche plein texte.

La question du PDF est maitrisable en  privilégiant le dépôt des PDFs éditeurs.

Cela vous semble-t-il envisageable ? Y voyez-vous d'ores et déjà des limitations ?

**Comment by CarolineTerrier** [comment]
Bonjour,

Question 1) Myriam et moi pensons qu'une css "word-break" est inappropriée. 

- Le premier problème vient du fait qu'il n'est pas toujours possible de placer des césures dans un tableau. Par exemple, dans votre document, on voit mal où mettre des césures supplémentaires pour la tableau "Relevé météorologique de Reykjavik".

- D'autre part, même lorsque les césures sont possibles, si le tableau comporte trop de colonnes, ça ne l’empêchera pas de dépasser de la largeur de la maquette.

Question 2)
Que l'éditeur dispose d'un fichier pivot avec un lien vers l'image du tableau ne nous pose aucun problème. Mais, pour ce qui concerne le fichier importé sous Lodel, la transcription du contenu en texte caché n'est pas d'actualité sur nos plateformes. 

En ce qui concerne la question des PDF, nous ne souhaitons pas empêcher les éditeurs qui le souhaiteraient d'utiliser notre générateur de PDF. Par ailleurs, il reste pour tous les éditeurs, la question de la génération des Epub par notre générateur.
